### PR TITLE
fix: update readme.md, update .gitignore to exclude ide created files

### LINKED ISSUE #2: [FEATURE] Update project readme
# Background
Right now our readme comes from the default javascript project template.
# Requirements
Update the readme to reflect our actual project details
# Tasks
- [ ] update each section of the current readme file

### PR DESCRIPTION
**Pull request by kofimokome**
## Description
- Update readme.md to reflect what we are working on
- Add Project Description
- Add list of authors and contributors
- Remove old codacy logo from readme
- Update .gitignore to exclude IDE specific files (**.idea/** in my case)
- @ayeahgodlove will continue from here

Fixes #2 

## Checklist:

- [ ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by ayeahgodlove — DISMISSED** [review]
Great work @kofimokome

**Review by kraulain — DISMISSED** [review]
Looks good to me

**Review by cyprian-nziim — APPROVED** [review]
Looks good nice setup.

**Review by kraulain — APPROVED** [review]
👍

**Review by ayeahgodlove — COMMENTED** [review]
looks good

**Review by ayeahgodlove — APPROVED** [review]

**Pull request merged**
