### PR TITLE
[FEATURE] Set up continuous deployment to GitHub pages #5 

### LINKED ISSUE #5: [FEATURE] Set up continuous deployment to GitHub pages
# Background
Since our focus is on frontend development, we can set up our repository to be automatically hosted on GitHub pages, that way, we can view a live version of our app at any point in time by visiting a simple link.
# Requirements
Configure GitHub pages hosting for our repository

### PR DESCRIPTION
**Pull request by honorezemagho**
## Description
[FEATURE] Set up continuous deployment to GitHub pages #5 

## Checklist:
-  Fork the repository
- Build files ready for production using parcel with the command "parcel build"
-  Fixing issues with relative path by adding ./ at the before url. e.g : "./login-page.html" instead  of "/login-html" 
- Setup Continious Deployment to with github pages using the branch "develop" on push or pull request

## Setup it in the project
- run npm install
- run `npm run deploy`. This command will first run `npm run build` build files using `parcel` and store it in `build` folder.
After this the command will create automatically new branch `gh-pages` to your github repository and push `build` folder inside.

-  create a secret in your github account and name it `MY_TOKEN`  you can put whatever you want as a secret and github will automatically encrypt it. Github will use it to trigger action that is defined in the workflow.

-  run 'git push' to push your code into your github repository and this will launch the trigger and deploy it to github pages of the project.

## How Has This Been Tested?
I have tested it with my own forked repository. Take  a look  [here](https://honorezemagho.github.io/Team-222-SDG2-P1/)

### CODE REVIEW

**Review by kofimokome — COMMENTED** [review]
Nice job @honorezemagho 
Even though I can confirm from your fork that the code works, I may still want to test myself so I have forked your fork in order to test it myself. The page has been set up [here](http://kofimokome.github.io/Team-222-SDG2-P1/) but GitHub says the site can not be found. 
If I am unable to host it with the fork **of your fork** then, I will review your changes and approve since it works on your fork

**Comment by honorezemagho** [comment]
Before sending you have to define a secret in your github repository for setting up automatic deployment and name it "MY_TOKEN".  After this run "npm run deploy"and do it again it will work now.

--Summary
- define secret in your github repository and name  it "MY_TOKEN"
- run "npm run deploy" before pushing  your code

**Review by kraulain — APPROVED** [review]
thanks for the great work.
I approve of this. 👍 
but I wish this could be improved in the future.
- no need to fork the project just create a separate branch
- improve the `readme` file  by adding the instructions required to build and deploy to gh-pages

**Review by kofimokome — APPROVED** [review]
Thanks for the reply @honorezemagho .

**Review by ayeahgodlove — APPROVED** [review]
Well done.
Build i had an error doing 'npm run deploy'

**Pull request merged**
